In [1]:
import numpy as np

In [2]:
a = np.arange(0,20,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [3]:
z = np.zeros((2,2))
print(z)

[[0. 0.]
 [0. 0.]]


In [4]:
o = np.ones((2,2))
print(o)

[[1. 1.]
 [1. 1.]]


In [5]:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
e0 = np.empty([3,3], dtype=float)
print(e0)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
print(e.ndim)

2


In [9]:
a0 = np.array([0,1,2,3,4], ndmin=2)
print(a0)

[[0 1 2 3 4]]


In [10]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])
a1 = np.append(a1, a2)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
a3 = np.concatenate((a1,a2))
print(a3)

[ 1  2  3  4  5  6  7  8  9 10  6  7  8  9 10]


In [12]:
a4 = np.array([1,2,3,4,5,6], dtype=float)
print(a4)

[1. 2. 3. 4. 5. 6.]


In [13]:
print(a0.shape)

(1, 5)


In [14]:
print(z.size)

4


In [15]:
a5 = np.arange(6).reshape((3, 2))
print(a5)

[[0 1]
 [2 3]
 [4 5]]


In [16]:
a5[1,1]

3

In [17]:
a6 = np.array([[12, 15], [10, 1]])
a6 = np.sort(a6, axis = 0)        
print ("Along first axis : \n", a6) 

Along first axis : 
 [[10  1]
 [12 15]]


In [18]:
r = np.random.rand(5)
print(r)

[0.2491473  0.4144935  0.15589967 0.75648563 0.72474359]
